### PR TITLE
FIX `num_points` parameter deprecation in `imagepolygon()`

### LINKED ISSUE #17: Deprecated Functionality: imagepolygon(): Using the $num_points parameter is deprecated PHP 8.1
https://github.com/laminas/laminas-barcode/blob/0fae0391d77e7f4e23a3a2154046754e403f20cb/src/Renderer/Image.php#L490-L509

Fix is to remove $numPoints from line 501.

```php
        if (! $filled) {
            return imagepolygon($this->resource, $points, $color);
        }
`

### PR DESCRIPTION
**Pull request by ls-youssef-jlidat**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

The parameter `num_points` has been deprecated in PHP 8.1
https://www.php.net/manual/en/function.imagepolygon.php
```
Error [8192]: imagepolygon(): Using the $num_points parameter is deprecated in /var/www/vendor/laminas/laminas-barcode/src/Renderer/Image.php on line 501
```

### CODE REVIEW

File: src/Renderer/Image.php [hunk 1]
```diff
@@ -498,7 +498,10 @@ protected function drawText($text, $size, $position, $font, $color, $alignment =
     protected function imageFilledPolygonWrapper($image, array $points, $numPoints, $color, $filled)
     {
         if (! $filled) {
-            return imagepolygon($this->resource, $points, $numPoints, $color);
+            if (PHP_VERSION_ID < 80100) {
+                return imagepolygon($this->resource, $points, $numPoints, $color);
+            }
```
Comment (froschdesign) [inline src/Renderer/Image.php]: This part is not necessary as PHP version 8.1 is the minimum for this package:

https://github.com/laminas/laminas-barcode/blob/e8e85eb77c0b9768846e7e97a285485790e4f942/composer.json#L27-L28

**Review by froschdesign — CHANGES_REQUESTED** [review]

File: src/Renderer/Image.php (hunk 1 above)
Comment (ls-youssef-jlidat) [reply src/Renderer/Image.php]: Good point! I removed the version check and the usage of `$numPoints` (It's assumed to be `count($points)/2`)

**Comment by ls-youssef-jlidat** [comment]
Hey @froschdesign, Is there any chance we could get this one merged soon? Thanks a bunch!

**Review by gsteel — APPROVED** [review]
Thanks @ls-youssef-jlidat
